### ISSUE TITLE
tagged version 4.3.5 doesn't seems ready for release

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-engine-sdk-go#169]
## The problem

tagged version 4.3.5 includes still 
`<version>4.3.5-SNAPSHOT</version>`
instead of 
`<version>4.3.5</version>`

rpmbs built from tag are the generated with git hash like in https://jenkins.ovirt.org/job/standard-manual-runner/334/ with 4.3.4 versioning instead of 4.3.5

**Comment by sandrobonazzola** [comment]
@imjoey any plan to issue a 4.3.5.1 or a 4.3.6 fixing the release?

**Comment by imjoey** [comment]
Hi @sandrobonazzola , I'm so sorry for not noticing this. I will fix it right now.

**Comment by imjoey** [comment]
Hi @sandrobonazzola , this issue gets fixed in PR #171 within a new release 4.3.6. Also I have seen the build running for check_pr passed and the version 4.3.6 rpm generated. But I did not find the build which is target to the tag 4.3.6. Could you please lead me to the URL for tag build that I could follow it and close this issue once the final 4.3.6 rpm is successfully generated. Thanks.

**Comment by sandrobonazzola** [comment]
Here's the 4.3.6 build: https://jenkins.ovirt.org/job/oVirt_ovirt-engine-sdk-go_standard-on-ghpush/15/

**Comment by imjoey** [comment]
Thanks @sandrobonazzola . Could this issue be closed? 😄

**Comment by sandrobonazzola** [comment]
yes, closing
